services:
    app.repository.file:
        class: AppBundle\Repository\FileRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle:File']
    app.storage:
        class: AppBundle\Storage\Storage
        arguments: ["@app.repository.file", "@oneup_flysystem.storage_filesystem"]
